export default {
    INIT_TOKEN: 'INIT_TOKEN',
    PURGE_TOKEN: 'PURGE_TOKEN',

    FETCH_STOCKS_STARTED: 'FETCH_STOCKS_STARTED',
    FETCH_STOCKS_COMPLETE: 'FETCH_STOCKS_COMPLETE',

    FETCH_PORTFOLIO_STARTED: 'FETCH_PORTFOLIO_STARTED',
    FETCH_PORTFOLIO_COMPLETE: 'FETCH_PORTFOLIO_COMPLETE',

    ADD_FAVOURITE_STARTED: 'ADD_FAVOURITE_STARTED',
    ADD_FAVOURITE_COMPLETE: 'ADD_FAVOURITE_COMPLETE',

    REMOVE_FAVOURITE_STARTED: 'REMOVE_FAVOURITE_STARTED',
    REMOVE_FAVOURITE_COMPLETED: 'REMOVE_FAVOURITE_COMPLETED'
};
