name: Deploy

on:
  push:
    branches:
      - master

env:
  FRONTEND_BUCKET: cs4471-group1-project-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          REACT_APP_LOGIN_URL: https://auth.cs4471-stock-platform.xyz/login?response_type=token&client_id=1c6ks0s77dbtdm8694au9smfn0&redirect_uri=https://cs4471-stock-platform.xyz/
          REACT_APP_LOGOUT_URL: https://auth.cs4471-stock-platform.xyz/logout?response_type=token&client_id=1c6ks0s77dbtdm8694au9smfn0&redirect_uri=https://cs4471-stock-platform.xyz/
          REACT_APP_AUTH_ENABLED: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1
      - name: Deploy
        run: aws s3 sync build/ s3://$FRONTEND_BUCKET
